project:
  type: website
  output-dir: docs

# Meta
# description-meta: "Suehyun Kim's academic website"
# author-meta: "Suehyun Kim"

website:
  title: "Suehyun Kim"
 
  navbar:
    background: light  # You can change the background color here

    right:   # You can comment out all navigation items here if you just like to keep the index page only
      - text: About
        href: about.qmd        
      - text: Research
        menu:
          - text: Publications & Talks
            href: publications.qmd
          - text: Projects
            href: posts.qmd                        
      - text: CV 
        href: cv.qmd
      - text: Misc.
        href: misc.qmd
  
  page-navigation: true
  
  page-footer: 
    left: "Suehyun Kim &copy; <script>document.write(new Date().getFullYear())</script> Built on [Quarto Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) adapted by [Dr. Gang He](http://drganghe.github.io)" 
    center: ""
    right:  
      - icon: rss
        href: posts.xml
        target: _blank  
  
  search:
    location: navbar
    type: overlay
  
  # reader-mode: true

  draft-mode: unlinked
  
  open-graph: true
  
  site-url: "https://suehkim.github.io"
  
  google-analytics:
    tracking-id: "G-9P1EZF9E9B"
    anonymize-ip: true 



# format:
#   html:
#     theme: cosmo
#     css: styles.css
#     toc: true
#     footnotes-hover: true
#     code-copy: true
#     code-link: true
#     code-overflow: wrap
#     fig-align: center
#     link-external-icon: false
#     link-external-newwindow: true
#     email-obfuscation: javascript
#     link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
#     include-in-header: "files/includes/_academic.qmd"

format: 
  html:
    theme:
      light:
        - cosmo
        - assets/my-theme-light.scss
    #   dark: 
    #     - cosmo
    #     - assets/silvia-theme-dark.scss
    #     - assets/silvia/colors-dark.scss
    # highlight-style:
    #   light: assets/silvia/a11y-light.theme
    #   dark: assets/silvia/a11y-dark.theme
    code-link: true
    pagetitle: "{{< meta title >}}"
    lightbox: true

execute: 
  freeze: auto
