---
title: "Curriculum Vitae"
page-layout: article
---

For my comprehensive CV, click [here](files/CV_SuehyunKim.pdf).

## Education

::: {.bulleted-mortarboard}
- **M.S. in Statistics**    
    Seoul National University   
    *2024–2026 (expected)*  
    
- **B.S. in Mathematical Sciences and Statistics**    
  Seoul National University   
  *2019–2024*, *Summa Cum Laude*  
:::

## Awards and Honors

- **Alumni Association President's Award (서울대학교 총동창회장상)**, Seoul National University, August 2024

- **Kwanjeong Scholarship**, Kwanjeong Educational Foundation, 2021–2023

- **GLEAP (Official Honor Society of SNU College of Natural Sciences)**, 2020–2021

- **Merit-Based Scholarship**, Seoul National University, 2019–2020

- **Dean's List**, SNU College of Natural Sciences, 2019–2024

## Teaching

Teaching experience at Seoul National University

- Spring 2026: **Regression Analysis and Lab. (326.313)**, Teaching Assistant

- Winter 2024: **Freshman Pre-College Course in Statistics**, Teaching Assistant

- Fall 2024: **Data Analysis and Lab. (M1399.001400)**, Teaching Assistant

- Spring 2024: **Statistics (F32.102)**, Peer Tutor
