---
title: Miscellaneous
page-layout: article
---

## Paper Reviews

Paper and book chapter reviews from the regular seminar of the Causal Inference Lab.

- **High-dimensional statistics: A non-asymptotic viewpoint**   
  Wainwright, M. J. (2019).     
  [ch2--ch4](files/bookreview_HDS.pdf) ·
  [ch15](files/260429_HDS_Ch15.pdf) ·
  [original book](https://doi.org/10.1017/9781108627771)

- **A nonparametric framework for treatment effect modifier discovery in high dimensions**    
  Boileau, P., Leng. N., Hejazi, N. S., van der Laan, M., & Dudoit, S. (2025). *JRSSB*          
  [paper review slides](files/paperreview_boileau.pdf) ·
  [original paper](https://doi.org/10.1093/jrsssb/qkae084)

- **Causal inference on distribution functions**    
    Lin, Z., Kong, D., & Wang, L. (2023). *JRSSB*          
  [paper review slides](files/paperreview_lin.pdf) ·
  [original paper](https://doi.org/10.1093/jrsssb/qkad008)

-   
  **Transfer learning between U.S. presidential elections: How should we learn from a 2020 ad campaign to inform 2024 ad campaigns?**   
  Miao, X., Zhao, J., & Kang, H. (2024). *arXiv preprint*   
  [paper review slides](files/paperreview_miao.pdf) ·
  [original paper](https://arxiv.org/abs/2411.01100)

- **Covariate-adaptive randomization inference in matched designs**      
  Pimentel, S. D., & Huang, Y. (2024). *JRSSB*  
  [paper review slides](files/paperreview_pimentel.pdf) ·
  [original paper](https://doi.org/10.1093/jrsssb/qkae033)

- **Finding influential subjects in a network using a causal framework**       
  Lee, Y., Buchanan, A. L., Ogburn, E. L., Friedman, S. R., Halloran, M. E., Katenka, N. V., Wu, J., & Nikolopoulos, G. K. (2023). *Biometrics*     
  [paper review slides](files/paperreview_lee.pdf) ·
  [original paper](https://doi.org/10.1111/biom.13841)


## Coursework

A list of my past coursework can be found [here](misc/coursework.qmd).