---
title: "Publications / Talks"
page-layout: article
---

::: {.text-end style="font-size: 0.75em; color: #717c84;"}
\*: Equally contributing co-authors
:::


1. **Mixing Samples to Address Weak Overlap in Observational Studies**  
  Jaehyuk Jang\*, <u>Suehyun Kim</u>\*, Kwonsang Lee. *Submitted.*  
  [[arXiv]](https://arxiv.org/abs/2411.10801v3)    <div style="height: 0.4rem;"></div>
    - *Nonparametric Inference in the Age of AI (Workshop)*, Department of Statistics, Seoul National University, Feb 2025. 
    - *European Causal Inference Meeting (EuroCIM)*, Ghent, Belgium, April 2025. *<span style="color: #717c84;">Oral presentation.</span>*
    - *American Causal Inference Conference (ACIC)*, Detroit, Michigan, May 2025. *<span style="color: #717c84;">Oral presentation.</span>* [[slides]](/files/ACIC_2025_mixing.pdf)
    - *Korean Statistical Society Summer Conference*, Gyeongju, Korea, June 2025. [[slides]](/files/KSS_2025_mixing.pdf)

::: {.spacer}
:::

2. **A Design-Based Matching Framework for Staggered Adoption with Time-Varying Confounding**  
    <u>Suehyun Kim</u> and Kwonsang Lee. *Preprint.* <div style="height: 0.4rem;"></div> 
    - *Korean Statistical Society Winter Conference*, Seoul, Korea, December 2025.
    - *European Causal Inference Meeting (EuroCIM)*, Oxford, United Kingdom, April 2026. *<span style="color: #717c84;">Oral presentation.</span>* [[slides]](/files/EuroCIM_2026_rtnm.pdf)